"""create cartas model tables

Revision ID: 22006a23e794
Revises: 0ee3bb3588ba
Create Date: 2026-08-13 08:59:22.842945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22006a23e794'
down_revision: Union[str, Sequence[str], None] = '0ee3bb3588ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carta_modelo',
    sa.Column('id_modelo', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('granularidade', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            granularidade IN (\n                'PROMOTOR_REDE',\n                'PDV'\n            )\n            ", name='ck_carta_modelo_granularidade'),
    sa.CheckConstraint("\n            tipo IN (\n                'ESTATICO',\n                'VARIAVEL'\n            )\n            ", name='ck_carta_modelo_tipo'),
    sa.PrimaryKeyConstraint('id_modelo')
    )
    op.create_index('ix_carta_modelo_ativo', 'carta_modelo', ['ativo'], unique=False)
    op.create_table('carta_modelo_rede',
    sa.Column('id_modelo_rede', sa.UUID(), nullable=False),
    sa.Column('id_modelo', sa.UUID(), nullable=False),
    sa.Column('rede', sa.String(length=160), nullable=False),
    sa.Column('rede_normalizada', sa.String(length=160), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_modelo'], ['carta_modelo.id_modelo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_modelo_rede'),
    sa.UniqueConstraint('id_modelo', 'rede_normalizada', name='uq_carta_modelo_rede')
    )
    op.create_index('ix_carta_modelo_rede_normalizada', 'carta_modelo_rede', ['rede_normalizada'], unique=False)
    op.create_table('carta_modelo_versao',
    sa.Column('id_versao', sa.UUID(), nullable=False),
    sa.Column('id_modelo', sa.UUID(), nullable=False),
    sa.Column('numero_versao', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            tamanho_bytes IS NULL\n            OR tamanho_bytes >= 0\n            ', name='ck_carta_modelo_versao_tamanho'),
    sa.CheckConstraint('numero_versao >= 1', name='ck_carta_modelo_versao_numero'),
    sa.ForeignKeyConstraint(['id_modelo'], ['carta_modelo.id_modelo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_versao'),
    sa.UniqueConstraint('id_modelo', 'numero_versao', name='uq_carta_modelo_numero_versao'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_carta_modelo_versao_hash', 'carta_modelo_versao', ['hash_sha256'], unique=False)
    op.create_index('ux_carta_modelo_versao_ativa', 'carta_modelo_versao', ['id_modelo'], unique=True, postgresql_where=sa.text('ativo = true'))
    op.create_table('carta_modelo_campo',
    sa.Column('id_campo', sa.UUID(), nullable=False),
    sa.Column('id_versao', sa.UUID(), nullable=False),
    sa.Column('nome_original', sa.String(length=200), nullable=False),
    sa.Column('chave_normalizada', sa.String(length=160), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordem >= 1', name='ck_carta_modelo_campo_ordem'),
    sa.ForeignKeyConstraint(['id_versao'], ['carta_modelo_versao.id_versao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_campo'),
    sa.UniqueConstraint('id_versao', 'chave_normalizada', name='uq_carta_modelo_campo_versao_chave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carta_modelo_campo')
    op.drop_index('ux_carta_modelo_versao_ativa', table_name='carta_modelo_versao', postgresql_where=sa.text('ativo = true'))
    op.drop_index('ix_carta_modelo_versao_hash', table_name='carta_modelo_versao')
    op.drop_table('carta_modelo_versao')
    op.drop_index('ix_carta_modelo_rede_normalizada', table_name='carta_modelo_rede')
    op.drop_table('carta_modelo_rede')
    op.drop_index('ix_carta_modelo_ativo', table_name='carta_modelo')
    op.drop_table('carta_modelo')
    # ### end Alembic commands ###
