"""create dim_promotor

Revision ID: c64a774365e8
Revises: 
Create Date: 2026-08-07 01:22:09.543686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64a774365e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_promotor',
    sa.Column('id_promotor', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("cpf ~ '^[0-9]{11}$'", name='ck_dim_promotor_cpf'),
    sa.PrimaryKeyConstraint('id_promotor')
    )
    op.create_index(op.f('ix_dim_promotor_cpf'), 'dim_promotor', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dim_promotor_cpf'), table_name='dim_promotor')
    op.drop_table('dim_promotor')
    # ### end Alembic commands ###
