"""create operational collection schema

Revision ID: fecd6c58f685
Revises: c64a774365e8
Create Date: 2026-08-07 01:31:26.647457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecd6c58f685'
down_revision: Union[str, Sequence[str], None] = 'c64a774365e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_pdv',
    sa.Column('id_pdv', sa.UUID(), nullable=False),
    sa.Column('codigo_origem', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('nome_pdv', sa.String(length=250), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cnpj IS NULL OR cnpj ~ '^[0-9]{14}$'", name='ck_dim_pdv_cnpj'),
    sa.PrimaryKeyConstraint('id_pdv')
    )
    op.create_index(op.f('ix_dim_pdv_cnpj'), 'dim_pdv', ['cnpj'], unique=False)
    op.create_index(op.f('ix_dim_pdv_codigo_origem'), 'dim_pdv', ['codigo_origem'], unique=True)
    op.create_table('dim_pergunta',
    sa.Column('id_pergunta', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('tipo_resposta', sa.String(length=30), nullable=False),
    sa.Column('aplica_sku', sa.Boolean(), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_resposta IN ('SIM_NAO', 'TEXTO', 'NUMERO', 'SELECAO')", name='ck_dim_pergunta_tipo'),
    sa.PrimaryKeyConstraint('id_pergunta')
    )
    op.create_index(op.f('ix_dim_pergunta_codigo'), 'dim_pergunta', ['codigo'], unique=True)
    op.create_table('dim_sku',
    sa.Column('id_sku', sa.UUID(), nullable=False),
    sa.Column('codigo_sku', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_sku')
    )
    op.create_index(op.f('ix_dim_sku_codigo_sku'), 'dim_sku', ['codigo_sku'], unique=True)
    op.create_table('fto_roteiro',
    sa.Column('id_roteiro', sa.UUID(), nullable=False),
    sa.Column('id_promotor', sa.UUID(), nullable=False),
    sa.Column('id_pdv', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pdv'], ['dim_pdv.id_pdv'], ),
    sa.ForeignKeyConstraint(['id_promotor'], ['dim_promotor.id_promotor'], ),
    sa.PrimaryKeyConstraint('id_roteiro'),
    sa.UniqueConstraint('id_promotor', 'id_pdv', name='uq_roteiro_promotor_pdv')
    )
    op.create_index('ix_roteiro_promotor_ativo', 'fto_roteiro', ['id_promotor', 'ativo'], unique=False)
    op.create_table('fto_pesquisa',
    sa.Column('id_pesquisa', sa.UUID(), nullable=False),
    sa.Column('id_roteiro', sa.UUID(), nullable=False),
    sa.Column('id_promotor', sa.UUID(), nullable=False),
    sa.Column('id_pdv', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latitude_inicio', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude_inicio', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('precisao_inicio_metros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('latitude_fim', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude_fim', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('precisao_fim_metros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('iniciada_em_dispositivo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_em_dispositivo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recebida_em_servidor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sincronizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('app_version', sa.String(length=30), nullable=True),
    sa.Column('criada_offline', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'EM_PREENCHIMENTO',\n                'FINALIZADA_LOCAL',\n                'SINCRONIZANDO',\n                'SINCRONIZADA',\n                'ERRO'\n            )\n            ", name='ck_pesquisa_status'),
    sa.ForeignKeyConstraint(['id_pdv'], ['dim_pdv.id_pdv'], ),
    sa.ForeignKeyConstraint(['id_promotor'], ['dim_promotor.id_promotor'], ),
    sa.ForeignKeyConstraint(['id_roteiro'], ['fto_roteiro.id_roteiro'], ),
    sa.PrimaryKeyConstraint('id_pesquisa')
    )
    op.create_index('ix_pesquisa_pdv', 'fto_pesquisa', ['id_pdv'], unique=False)
    op.create_index('ix_pesquisa_promotor', 'fto_pesquisa', ['id_promotor'], unique=False)
    op.create_index('ix_pesquisa_status', 'fto_pesquisa', ['status'], unique=False)
    op.create_table('fto_foto',
    sa.Column('id_foto', sa.UUID(), nullable=False),
    sa.Column('id_pesquisa', sa.UUID(), nullable=False),
    sa.Column('id_sku', sa.UUID(), nullable=True),
    sa.Column('tipo_evidencia', sa.String(length=30), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('arquivo_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('precisao_metros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capturada_em_dispositivo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recebida_em_servidor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_upload', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status_upload IN (\n                'PENDENTE',\n                'ENVIANDO',\n                'ENVIADA',\n                'ERRO'\n            )\n            ", name='ck_foto_status_upload'),
    sa.CheckConstraint("\n            tipo_evidencia IN (\n                'ANTES',\n                'DEPOIS',\n                'GIRO_ESTOQUE'\n            )\n            ", name='ck_foto_tipo_evidencia'),
    sa.ForeignKeyConstraint(['id_pesquisa'], ['fto_pesquisa.id_pesquisa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sku'], ['dim_sku.id_sku'], ),
    sa.PrimaryKeyConstraint('id_foto'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_foto_pesquisa_tipo', 'fto_foto', ['id_pesquisa', 'tipo_evidencia'], unique=False)
    op.create_index(op.f('ix_fto_foto_hash_sha256'), 'fto_foto', ['hash_sha256'], unique=False)
    op.create_table('fto_resposta',
    sa.Column('id_resposta', sa.UUID(), nullable=False),
    sa.Column('id_pesquisa', sa.UUID(), nullable=False),
    sa.Column('id_pergunta', sa.UUID(), nullable=False),
    sa.Column('id_sku', sa.UUID(), nullable=True),
    sa.Column('valor', sa.String(length=1000), nullable=False),
    sa.Column('respondida_em_dispositivo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recebida_em_servidor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pergunta'], ['dim_pergunta.id_pergunta'], ),
    sa.ForeignKeyConstraint(['id_pesquisa'], ['fto_pesquisa.id_pesquisa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sku'], ['dim_sku.id_sku'], ),
    sa.PrimaryKeyConstraint('id_resposta'),
    sa.UniqueConstraint('id_pesquisa', 'id_pergunta', 'id_sku', name='uq_resposta_pesquisa_pergunta_sku', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_resposta_pesquisa', 'fto_resposta', ['id_pesquisa'], unique=False)
    op.create_index('ix_resposta_sku', 'fto_resposta', ['id_sku'], unique=False)
    op.add_column('dim_promotor', sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('dim_promotor', sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_promotor', 'atualizado_em')
    op.drop_column('dim_promotor', 'criado_em')
    op.drop_index('ix_resposta_sku', table_name='fto_resposta')
    op.drop_index('ix_resposta_pesquisa', table_name='fto_resposta')
    op.drop_table('fto_resposta')
    op.drop_index(op.f('ix_fto_foto_hash_sha256'), table_name='fto_foto')
    op.drop_index('ix_foto_pesquisa_tipo', table_name='fto_foto')
    op.drop_table('fto_foto')
    op.drop_index('ix_pesquisa_status', table_name='fto_pesquisa')
    op.drop_index('ix_pesquisa_promotor', table_name='fto_pesquisa')
    op.drop_index('ix_pesquisa_pdv', table_name='fto_pesquisa')
    op.drop_table('fto_pesquisa')
    op.drop_index('ix_roteiro_promotor_ativo', table_name='fto_roteiro')
    op.drop_table('fto_roteiro')
    op.drop_index(op.f('ix_dim_sku_codigo_sku'), table_name='dim_sku')
    op.drop_table('dim_sku')
    op.drop_index(op.f('ix_dim_pergunta_codigo'), table_name='dim_pergunta')
    op.drop_table('dim_pergunta')
    op.drop_index(op.f('ix_dim_pdv_codigo_origem'), table_name='dim_pdv')
    op.drop_index(op.f('ix_dim_pdv_cnpj'), table_name='dim_pdv')
    op.drop_table('dim_pdv')
    # ### end Alembic commands ###
